# 1. Create a 3x3x3 array with random values 

In [ ]:
import numpy as np

arr = np.empty((3,3,3))
print(arr)

[[[2.31945086e-316 0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000 0.00000000e+000]]

 [[0.00000000e+000 0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000 0.00000000e+000]]

 [[0.00000000e+000 0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000 0.00000000e+000]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [ ]:
z = np.diag(1+np.arange(4), k =-1)
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [ ]:
array = np.array([[0,1], [1,0]])
z1 = np.tile(array, (4,4))
print(z1)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [ ]:
z = np.random.random((5,5))
Zmax , Zmin = z.max(), z.min()
z = (z-Zmin) / (Zmax -Zmin)
print(z)

[[0.41362561 0.27500787 0.61009726 0.1618269  0.83768901]
 [0.94829549 0.18133837 0.69094819 0.34526157 0.14210052]
 [0.17148466 0.30668915 0.26334953 0.28088822 0.40894815]
 [0.05522837 0.85975238 0.72716921 0.90797151 0.96287952]
 [0.68221245 0.34595276 0.86952    0.04989736 0.6844945 ]]
0.9628795218968479
0.049897360219101405
[[0.39839579 0.24656617 0.61359348 0.12259773 0.86287738]
 [0.98402594 0.14396887 0.70215045 0.32351586 0.10099119]
 [0.13317599 0.28126704 0.23379665 0.25300698 0.39327252]
 [0.00583912 0.88704363 0.74182375 0.93985862 1.        ]
 [0.69258209 0.32427293 0.89774223 0.         0.69508164]]


# 5.  How to find common values between two arrays?

In [ ]:
a = np.array([1,2,3,4,5,6])
b = np.array([4,5,6,7,8,9])
print(np.intersect1d(a,b))

[4 5 6]


# 6.How to get the dates of yesterday, today and tomorrow?

In [ ]:
date_today = np.datetime64("today", "D")
date_tomorrow = date_today + np.timedelta64(1, "D")
date_yesterday = date_today - np.timedelta64(1, "D")
print("Today is {0}\nTomrrow is {1}\nYesterday was {2}".format(date_today , date_yesterday, date_tomorrow))

Today is 2020-07-26
Tomrrow is 2020-07-25
Yesterday was 2020-07-27


# 7. Consider two random array A and B, check if they are equal

In [ ]:
a = np.random.random(5)
b = np.random.random(5)
equal = np.allclose(a,b)
print(equal)

False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [ ]:
z = np.random.random((10))
z[z.argmax()] = 0
print(z)

[0.5442652  0.09208017 0.57421444 0.         0.39692835 0.5631091
 0.65440954 0.18764549 0.52374301 0.00810827]


# 9. How to print all the values of an array?

In [ ]:
a = np.random.random((5,5))
for i in a:
  for index in i:
    print(index)

0.4292969784742606
0.8192306404594316
0.5836276595077438
0.214424351802175
0.18218179334794005
0.007694757285239384
0.37538603759421096
0.7951463777073955
0.4018345869825478
0.045206572461478745
0.6239105835544895
0.23399299997111012
0.9747987608323535
0.16099074609287467
0.44826862588676797
0.6105104049362694
0.7920935732372166
0.505915297302548
0.13840002815156627
0.27040746001845584
0.42708803640615445
0.06300297247561215
0.11278590581018466
0.010042195839661483
0.3517905611343787


# 10.Subtract the mean of each row of a matrix

In [ ]:
import numpy as np
means = []
a = np.random.random((6,6))
print(a)
for row in a:
  sum = 0
  total_elements = len(row)
  for i in row:
    sum = sum + i
  mean = sum / total_elements
  means.append(mean)

for i in range(0,len(means)):
  try:
    diff = means[i] - means[i + 1]
    print("difference betweeen {0}th term {1} and {2}th term  {3} is {4}".format(i, means[i], i+1, means[i+1], diff)) 
  except IndexError:
    pass

[[0.76015839 0.79695135 0.52668657 0.20286818 0.47851564 0.52530732]
 [0.59818809 0.46470676 0.66180033 0.7319475  0.45074314 0.06656791]
 [0.67849756 0.78867955 0.70685124 0.30446577 0.95962783 0.22369986]
 [0.46435781 0.86278034 0.14570248 0.38949413 0.42564855 0.28464741]
 [0.60720964 0.25822747 0.8278659  0.90967374 0.72418212 0.18245595]
 [0.12205958 0.29642902 0.58635102 0.66131421 0.4455072  0.91340704]]
difference betweeen 0th term 0.5484145721698632 and 1th term  0.4956589548897558 is 0.052755617280107414
difference betweeen 1th term 0.4956589548897558 and 2th term  0.61030363464548 is -0.11464467975572418
difference betweeen 2th term 0.61030363464548 and 3th term  0.4287717863291512 is 0.1815318483163288
difference betweeen 3th term 0.4287717863291512 and 4th term  0.58493580391265 is -0.1561640175834988
difference betweeen 4th term 0.58493580391265 and 5th term  0.5041780119052864 is 0.08075779200736355


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

# 12.How to get the diagonal of a dot product?

In [ ]:
a = np.random.random((5,5))
b = np.random.random((5,5))
z = a.dot(b)
print(np.diag(z))

[1.39326891 1.39773482 0.84334221 0.72834621 0.9636068 ]


# 13.How to find the most frequent value in an array?

In [ ]:
x = np.random.randint(0,10,30)
print(np.bincount(x).argmax())

2


# 14.How to get the n largest values of an array

In [ ]:
x = np.random.random(10)
y = np.argsort(x)
print(x,y)

[0.22184744 0.22396038 0.53036401 0.9427242  0.97119965 0.69190802
 0.597304   0.41834854 0.6143796  0.17830154] [9 0 1 7 2 6 8 5 3 4]


# 15.How to create a record array from a regular array?

In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = a[0:2, 0:2]
print(a)
print("-----------")
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
-----------
[[1 2]
 [5 6]]
